version: "3"
services:
    application:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: tui_app
        restart: "no"
        environment:
            - PORT=4000
            - DB_CONNECTION_STRING=mongodb://root:Teste123@tui_db:27017
            - API_KEY=8GGCq3GQYdN8NFx7ILxG6TLEiMvKG1rp
            - API_SECRET=UHzx0dGRhUkJqynj
        volumes:
            - ".:/project"
        ports:
            - 4000:4000
            - 4001:4001
        command: bash -c "npm install ; npm run dev"

    database:
        image: mongo
        container_name: tui_db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=Teste123
        ports:
            - 27017:27017
